### ISSUE TITLE
There was an error converting file to pdf

### ISSUE THREAD

**Issue by karnatikirankumar** [tienle/docsplit-paperclip-processor#9]
This conversion is working locally, but when we upload(pushed) into the server its not working.... it displaying as "there was error converting some file to pdf". 
Is office(libreoffice or openoffice) software is must in os? , 
My server os is centos.

**Comment by tienle** [comment]
Yes. You need to install office in your OS.

**Comment by karnatikirankumar** [comment]
My server is centos , i have installed libreoffice but still iam getting the same error when uploading doc files. Can you please suggest me on the issue.
